# Generated by Django 2.2.11 on 2020-03-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivo',
            old_name='arquivos',
            new_name='arquivo',
        ),
    ]
